sql_spalten = [
    'qah',
    'calc_ima',
    'cycle',
    'ecellv',
    'freqhz',
    'temperaturec',
    'imzohm',
    'rezohm',
    'zohm',
    'phasezdeg',
    'calc_rezohm',
    'calc_imzohm',
    'qchargemah',
    'qqomah',
    'energyWh',
    'ImA',
    'times',
    'calc_times',
    'datei',
    'typ'
]

mes_spalten = {
    "flags": "flags",
    "Ns": "ns",
    "I Range": "i_range",
    "time/s": "times",
    "control/V/mA": "control_v_ma",
    "control/mA": "control_ma",
    "Ewe/V": "ecellv",
    "I/mA": "ima",
    "dq/mA.h": "qah",
    "(Q-Qo)/mA.h": "qqomah",
    "|Energy|/W.h": "energywh",
    "freq/Hz": "freqhz",
    "|Z|/Ohm": "zohm",
    "Phase(Z)/deg": "phasezdeg",
    "Q charge/discharge/mA.h": "qchargemah",
    "half cycle": "half_cycle",
    "Temperature/°C": "temperaturec",
    "z cycle": "z_cycle",
    "Energy charge/W.h": "energy_charge_wh",
    "Energy discharge/W.h": "energy_discharge_wh",
    "Capacitance charge/µF": "capacitance_charge_uf",
    "Capacitance discharge/µF": "capacitance_discharge_uf",
    "step time/s": "step_time_s"
}