sql_spalten = [
    'QAh',
    'Calc_ImA',
    'Cycle',
    'EcellV',
    'freqHz',
    'TemperatureC',
    'ImZOhm',
    'ReZOhm',
    'ZOhm',
    'PhaseZdeg',
    'calc_ReZOhm',
    'calc_ImZOhm',
    'QchargemAh',
    'QQomAh',
    'EnergyWh',
    'ImA',
    'times',
    'calc_times',
    'Messung',
    'Typ'
]

mes_spalten = {
    "flags": "flags",
    "Ns": "ns",
    "I Range": "i_range",
    "time/s": "times",
    "control/V/mA": "control_v_ma",
    "Ewe/V": "EcellV",
    "I/mA": "ImA",
    "dq/mA.h": "QAh",
    "(Q-Qo)/mA.h": "QQomAh",
    "|Energy|/W.h": "EnergyWh",
    "freq/Hz": "freqHz",
    "|Z|/Ohm": "ZOhm",
    "Phase(Z)/deg": "PhaseZdeg",
    "Q charge/discharge/mA.h": "QchargemAh",
    "half cycle": "half_cycle",
    "Temperature/°C": "TemperatureC",
    "z cycle": "z_cycle",
    "Energy charge/W.h": "energy_charge_wh",
    "Energy discharge/W.h": "energy_discharge_wh",
    "Capacitance charge/µF": "capacitance_charge_uf",
    "Capacitance discharge/µF": "capacitance_discharge_uf",
    "step time/s": "step_time_s"
}